[theme]
base="light"
primaryColor="#4CAF50"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FFFFFF"
textColor="#000000"
font="sans serif"
[theme]
base="dark"
primaryColor="#4CAF50"
backgroundColor="#000000"
secondaryBackgroundColor="#121212"
textColor="#FFFFFF"
font="sans serif"


